apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2026-04-29T10:22:55Z"
  name: k8s.taskbymara.online
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://taskapp-kops-state-amara/k8s.taskbymara.online
  dnsZone: taskbymara.online
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.28.5
  masterPublicName: api.k8s.taskbymara.online
  networkCIDR: 10.0.0.0/16
  networkID: vpc-056f3cf5ded9843ff
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.0.10.0/24
    id: subnet-0b102d3947588aac3
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.0.11.0/24
    id: subnet-0b56673011f57bce6
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.0.12.0/24
    id: subnet-01d26872971aca654
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.0.1.0/24
    id: subnet-08ea539191a6bc6a9
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.0.2.0/24
    id: subnet-0a57e70763aa55337
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.0.3.0/24
    id: subnet-033929c4727535704
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    bastion:
      bastionPublicName: bastion.k8s.taskbymara.online
    dns:
      type: Public
