apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: taskapp
type: Opaque
stringData:
  POSTGRES_DB: taskapp
  POSTGRES_USER: taskapp
  POSTGRES_PASSWORD: TaskApp2024!
  DATABASE_URL: postgresql://taskapp:TaskApp2024!@postgres:5432/taskapp
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: taskapp
  DATABASE_USER: taskapp
  DATABASE_PASSWORD: TaskApp2024!